// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCogdSqE5Qdn9qEsvPF6-z2dv4sreUUTl4',
    appId: '1:364992655047:web:b5c71ced7c825ac8df58e2',
    messagingSenderId: '364992655047',
    projectId: 'fir-tutorial-743d6',
    authDomain: 'fir-tutorial-743d6.firebaseapp.com',
    storageBucket: 'fir-tutorial-743d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvfkWdtp1zMexbOUKwAHED1dzPsYyQcOI',
    appId: '1:364992655047:android:da81f0ab6b64b77cdf58e2',
    messagingSenderId: '364992655047',
    projectId: 'fir-tutorial-743d6',
    storageBucket: 'fir-tutorial-743d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWt1OiraNhbAm3dMDwi3GvRBGsrLoFVAE',
    appId: '1:364992655047:ios:724650a7bb219af2df58e2',
    messagingSenderId: '364992655047',
    projectId: 'fir-tutorial-743d6',
    storageBucket: 'fir-tutorial-743d6.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWt1OiraNhbAm3dMDwi3GvRBGsrLoFVAE',
    appId: '1:364992655047:ios:724650a7bb219af2df58e2',
    messagingSenderId: '364992655047',
    projectId: 'fir-tutorial-743d6',
    storageBucket: 'fir-tutorial-743d6.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTutorial',
  );
}
